class Views::Widgets::Forms::DefaultFormWidget < Views::Widgets::Base

  def content
    if ActiveSupport::Dependencies.search_for_file("/#{controller.controller_path}/form_widget.rb")
      widget("Views::#{controller.controller_path.camelize}::FormWidget".constantize)
    else
      text "form undefined / later autogenerated"
    end
  end

end