#!/bin/bash
# based on http://blog.raphinou.com/2008/12/capistrano-deployment-for-jetty-rails.html

# --- START SETTINGS TO EDIT ---
#add the JRE bin directory to path
PATH=$PATH:/usr/lib/jvm/java-6-sun-1.6.0.12/jre/bin/
#Base directory for deployment
# BASE_DIR=/home/railshost/apps/dingbank
BASE_DIR="$(PWD)/../"
#Jruby executable to use
# JRUBY=/usr/bin/jruby
JRUBY=$(which jruby)
# --- END SETTINGS TO EDIT ---

PID_FILE=$BASE_DIR/shared/pids/jetty_rails.pid
